file_wrapper.h: add missing include for musl
this fixes:
| In file included from ../webrtc-audio-processing-1.3/webrtc/rtc_base/system/file_wrapper.cc:11:
| ../webrtc-audio-processing-1.3/webrtc/rtc_base/system/file_wrapper.h:86:21: error: 'int64_t' has not been declared

if built with musl libc

Signed-off-by: Markus Volk <f_l_k@t-online.de>